config/routes.rb
Bannermaker::Application.routes.draw do
  resources :campaigns

  root 'landing#index'

  resources :campaigns

  get 'get_banner', to: 'get_banner#index'

  get 'othersite', to: 'other_site#index'

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  validates :name, :link, :image, presence: true

  has_attached_file :image, :styles => {:medium => "200x200>", :thumb => "100x100>"}
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :set_campaign, only: [:show, :edit, :update, :destroy]

  def index
    @campaigns = Campaign.all
  end

  def show

    click = params[:click]

    if click

      @all_click = @campaign.click.to_i + 1
      @all_show = @campaign.show
      @conversion = ((@all_click.to_f/@all_show.to_f)*100).round(1)
      @campaign.update(click: @all_click, conversion: @conversion)

      @show_results = nil

      Danthes.publish_to "/campaigns/#{@campaign.id}", show: @all_show, click: @all_click, conversion: @conversion

      redirect_to @campaign.link

    else
      @show_results = true
    end

  end

  def new
    @campaign = Campaign.new
  end

  def edit
  end

  def create
    @campaign = Campaign.new(campaign_params)

    if @campaign.save
      redirect_to campaigns_path, notice: 'Campaign was successfully created.'
    else
      render 'campaigns/edit'
    end

  end

  def update
      if @campaign.update(campaign_params)
        redirect_to campaigns_path, notice: 'Campaign was successfully updated.'
      else
        render 'campaigns/edit'
      end
  end

  def destroy
    @campaign.destroy
    redirect_to campaigns_url, notice: 'Campaign was successfully deleted.'
  end


  private
    def set_campaign
      @campaign = Campaign.find(params[:id])
    end

    def campaign_params
      params.require(:campaign).permit(:name, :link, :image)
    end
end

app/controllers/get_banner_controller.rb
class GetBannerController < ApplicationController

  if ENV['RAILS_ENV'] == 'test'
    require 'simplecov'
    SimpleCov.start 'rails'
    puts "required simplecov"
  end

  layout false

  # Страница-баннер
  def index

    # Берем рандомную компанию из всех
    campaigns = Campaign.all
    if campaigns.length>0
      id = rand(campaigns.count)
      @campaign = campaigns[id]

      # Добавляем просмотр баннеру компании
      show = @campaign[:show]

      if show
        @show = show + 1
      else
        @show = 1
      end

      # Обновляем эту компанию с новым количесвтом просмотров и отношением показов и кликов
      conversion = ((@campaign.click.to_f/@show.to_f)*100).round(1)
      @campaign.update(show: @show, conversion: conversion)

      Danthes.publish_to "/campaigns/#{@campaign.id}", show: @show, click: @campaign.click.to_i, conversion: conversion

    else
      render text: 'нет рекламных кампаний'
    end

  end

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

  def index
  end

end

app/controllers/other_site_controller.rb
class OtherSiteController < ApplicationController

  layout false

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaign_helper.rb
module CampaignHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/get_banner_helper.rb
module GetBannerHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/other_site_helper.rb
module OtherSiteHelper
end

app/views/campaigns/_form.html.slim
.well
  = simple_form_for(@campaign) do |f|
    = f.error_notification

    .form-inputs
      = f.input :name
      = f.input :link
      = f.input :image
    .clearfix

    .margin-top-20
    .form-group
      = f.button :submit, class: 'span3 offset1'

app/views/campaigns/edit.html.slim
h1 Editing campaign
.margin-top-30
== render 'form'

= link_to 'Show', @campaign
'|&nbsp;&nbsp;
= link_to 'Back', campaigns_path

app/views/campaigns/index.html.slim
h1 Listing campaigns
.margin-top-30


table.table.table-striped.table-hover

  tr
    th Image
    th Name
    th Link
    th
    th
    th

  - @campaigns.each_with_index do |campaign, index|
    tr id="#{index+1}"
      td
        - if campaign.image.present?
          div style="background: url(#{campaign.image.url(:thumb)}) no-repeat center; background-size: cover;"
        - else
          i.no_image.fa.fa-file-o
      td = campaign.name
      td = campaign.link
      td = link_to 'Edit', edit_campaign_path(campaign)
      td = link_to 'Show', campaign_path(campaign)
      td = link_to 'Destroy', campaign, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Campaign', new_campaign_path
.clearfix

app/views/campaigns/new.html.slim
h1 New campaign
.margin-top-30
== render 'form'

= link_to 'Back', campaigns_path

app/views/campaigns/show.html.slim
p#notice = notice


h2
  = @campaign.name
.margin-top-30
/javascript:
/  Danthes.debug = true

= subscribe_to "/campaigns/#{@campaign.id}"


- if @show_results
  table.table.table-striped.table-hover
    tr
      th Image
      th Show
      th Click
      th Conversion, %
    tr.big
      td
        - if @campaign.image.present?
          div.show style="background: url(#{@campaign.image.url(:medium)}) no-repeat center; background-size: cover;"
        - else
          i.no_image.fa.fa-file-o
      td#show  = @campaign.show ? @campaign.show : 0
      td#click = @campaign.click ? @campaign.click : 0
      td#conversion = @campaign.conversion ? @campaign.conversion : 0.0



= link_to 'Back', campaigns_path
javascript:
   Danthes.subscribe("/campaigns/#{@campaign.id}", function (data, channel) {
     $("#show").text(data.show);
     $("#click").text(data.click);
     $("#conversion").text(data.conversion);
   });

app/views/get_banner/index.slim
= link_to campaign_path(id: @campaign.id, click: @campaign.click ? @campaign.click : 0 ), target: '_blank' do
  - if @campaign.image_file_name.present?
    = image_tag @campaign.image.url(:medium)
  - else
    p нет изображения


/ TEST
/p = @campaign.name

app/views/landing/index.slim
.row-fluid

  h1.text-center Get more people to visit your website
  .margin-top-40
  .text-center
    = link_to  new_campaign_path do
      .btn.btn-primary.big Make your banner!

.margin-top-55
hr

.row-fluid

  h1.text-center Make money with Banner Ads
  .margin-top-30
  h3.text-center Paste this code on your site

  .margin-top-40
  .text-center
    = text_area_tag  nil, '<iframe frameborder="none" height="200" marginheight="0" marginwidth="0" src="/get_banner" width="200"></iframe>', escape: false, class: 'embed_code', readonly: true

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "Bannermaker"
    = csrf_meta_tags

    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"

    /  WEINRE DEBUG
    /= javascript_include_tag "http://192.168.1.49:8080/target/target-script-min.js#anonymous"

    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"



  body
    nav.navbar.navbar-default role="navigation"
      .container-fluid

        .navbar-header
          button.navbar-toggle type="button"  data-toggle="collapse" data-target=".nav-collapse"
            span class="sr-only" Toggle navigation
            span class="icon-bar"
            span class="icon-bar"
            span class="icon-bar"
          a class="navbar-brand" href="/" Bannermaker
          .container-fluid.nav-collapse
            ul.nav.navbar-nav
              li = link_to "All campaigns", campaigns_path


    #wrap.container-fluid

      .container
        .row-fluid
          .span12.margin-top-20

            = bootstrap_flash
            = yield

      footer
        p &copy; Bannermaker 2014